name: DEV Deployment

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      # Checkout Java project
      - name: Checkout Code
        uses: actions/checkout@v4


      # Setup Java 17
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven


      # Build WAR using Maven
      - name: Build WAR
        run: |
          mvn clean package


      # Configure SSH
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh

          echo "${{ secrets.DEV_SSH_KEY }}" > ~/.ssh/dev_key

          chmod 600 ~/.ssh/dev_key

          ssh-keyscan -H ${{ secrets.DEV_HOST }} >> ~/.ssh/known_hosts


      # Copy WAR to DEV EC2
      - name: Copy WAR to DEV EC2
        run: |
          scp -i ~/.ssh/dev_key \
            target/*.war \
            ec2-user@${{ secrets.DEV_HOST }}:/tmp/neontask-dev.war


      # Deploy WAR to Tomcat
      - name: Deploy to Tomcat
        run: |
          ssh -i ~/.ssh/dev_key \
            ec2-user@${{ secrets.DEV_HOST }} << 'EOF'

            echo "Stopping Tomcat..."

            sudo systemctl stop tomcat


            echo "Removing old DEV application..."

            sudo rm -rf /opt/tomcat/webapps/neontask-dev

            sudo rm -f /opt/tomcat/webapps/neontask-dev.war


            echo "Copying new DEV WAR..."

            sudo mv /tmp/neontask-dev.war \
              /opt/tomcat/webapps/neontask-dev.war


            echo "Setting permissions..."

            sudo chown tomcat:tomcat \
              /opt/tomcat/webapps/neontask-dev.war


            echo "Starting Tomcat..."

            sudo systemctl start tomcat


            echo "Checking Tomcat..."

            sudo systemctl status tomcat --no-pager


            echo "DEV deployment completed!"

          EOF


      # Deployment result
      - name: DEV Deployment Successful
        run: |
          echo "========================================"
          echo "       DEV DEPLOYMENT SUCCESSFUL"
          echo "========================================"
          echo "Application:"
          echo "http://${{ secrets.DEV_HOST }}:8080/neontask-dev"